/**
 * Fabricated sample data for the Finer OS interactive demo.
 *
 * ⚠️ Everything here is FICTIONAL. KOL handles are invented personas (no real
 * person), tickers/prices/returns are illustrative, and no value reflects a
 * real backtest. The demo runs entirely in the browser with zero backend.
 */
import type { Kol, StageDetail, TradeAction } from "./types";

const BENCHMARK = [0, 1.1, 2.0, 1.2, 2.5, 3.0, 2.2, 3.5, 4.0, 3.2, 3.6, 3.0];
const DATES = [
  "03-02", "03-09", "03-16", "03-23", "03-30", "04-06",
  "04-13", "04-20", "04-27", "05-01", "05-05", "05-08",
];

function series(values: number[]) {
  return values.map((value, i) => ({
    date: DATES[i],
    value,
    benchmark: BENCHMARK[i],
  }));
}

// ---- trader_ji / 老纪 — 个股短线 ---------------------------------------------

const TA_JI_MAOTAI: TradeAction = {
  trade_action_id: "TA-trader_ji-001",
  timestamp: "2026-03-12T09:35:00+08:00",
  ticker: "600519",
  company_name: "贵州茅台",
  market: "SH",
  direction: "bullish",
  summary: "茅台回踩 1580 支撑，缩量企稳分两批做多",
  action_chain: [
    {
      sequence: 1,
      action_type: "long",
      trigger_type: "support_resistance",
      trigger_condition: "回踩 1580 一带且缩量企稳",
      target_price_low: 1560,
      target_price_high: 1620,
      position_size_pct: 0.3,
      notes: "首批 30% 仓位，跌破 1540 止损",
    },
    {
      sequence: 2,
      action_type: "long",
      trigger_type: "breakout",
      trigger_condition: "放量站上 1660 加仓",
      target_price_low: 1660,
      target_price_high: 1700,
      position_size_pct: 0.2,
      notes: "second tranche",
    },
  ],
  intent_id: "INT-trader_ji-001",
  policy_id: "POL-global-base-v1",
  evidence_span_ids: ["EV-trader_ji-001-a", "EV-trader_ji-001-b"],
  canonical_trace_status: "canonical",
  confidence: 0.82,
  validation_status: "verified",
  model_version: "glm-5.1",
  extraction_method: "f3_intent + f4_policy + f5_execute",
  execution_timing: {
    intent_published_at: "2026-03-12T08:50:00+08:00",
    intent_effective_at: "2026-03-12T09:30:00+08:00",
    action_decision_at: "2026-03-12T09:30:00+08:00",
    action_executable_at: "2026-03-12T09:35:00+08:00",
    market: "SH",
    timezone: "Asia/Shanghai",
    market_session_at_publish: "pre_market",
  },
  intent: {
    intent_id: "INT-trader_ji-001",
    target_name: "贵州茅台",
    target_symbol: "600519",
    direction: "initiate_long",
    conviction: 0.78,
    sentiment_score: 0.6,
    time_horizon_hint: "swing",
    actionability: "actionable",
  },
  evidence: [
    {
      evidence_span_id: "EV-trader_ji-001-a",
      char_start: 10,
      char_end: 28,
      text: "茅台回踩 1580 一带我觉得是中线机会",
      confidence: 0.88,
      span_type: "claim",
    },
    {
      evidence_span_id: "EV-trader_ji-001-b",
      char_start: 38,
      char_end: 46,
      text: "缩量企稳就是上车点",
      confidence: 0.81,
      span_type: "rationale",
    },
  ],
  source_text:
    "今天聊聊白酒板块。茅台回踩 1580 一带我觉得是中线机会，基本面没出问题，缩量企稳就是上车点，仓位别一次打满，分两批。",
  source_published_at: "2026-03-12T08:50:00+08:00",
  backtest: {
    return_pct: 0.123,
    holding_days: 35,
    exit_reason: "target_reached",
    max_drawdown_pct: -0.052,
    sharpe_ratio: 0.91,
    backtest_period: "2026-03-12 — 2026-04-16",
  },
  rlhf: {
    rating: 4,
    is_correct: true,
    corrected_direction: null,
    corrections: ["目标价区间可适当放宽"],
    reviewer_id: "reviewer_demo",
    reviewed_at: "2026-03-18T14:30:00+08:00",
    review_notes: "方向正确，证据充分；目标价上沿略保守。",
  },
};

const TA_JI_CATL: TradeAction = {
  trade_action_id: "TA-trader_ji-002",
  timestamp: "2026-03-25T15:10:00+08:00",
  ticker: "300750",
  company_name: "宁德时代",
  market: "SZ",
  direction: "watchlist",
  summary: "宁德时代追高不划算，跌破 180 再看",
  action_chain: [
    {
      sequence: 1,
      action_type: "watch",
      trigger_type: "price_threshold",
      trigger_condition: "回落至 180 下方再评估",
      target_price_low: 172,
      target_price_high: 180,
      position_size_pct: null,
      notes: "未到价格不建仓",
    },
  ],
  intent_id: "INT-trader_ji-002",
  policy_id: "POL-global-base-v1",
  evidence_span_ids: ["EV-trader_ji-002-a"],
  canonical_trace_status: "canonical",
  confidence: 0.71,
  validation_status: "verified",
  model_version: "glm-5.1",
  extraction_method: "f3_intent + f4_policy + f5_execute",
  execution_timing: {
    intent_published_at: "2026-03-25T15:05:00+08:00",
    intent_effective_at: "2026-03-26T09:30:00+08:00",
    action_decision_at: "2026-03-26T09:30:00+08:00",
    action_executable_at: "2026-03-26T09:30:00+08:00",
    market: "SZ",
    timezone: "Asia/Shanghai",
    market_session_at_publish: "after_close",
  },
  intent: {
    intent_id: "INT-trader_ji-002",
    target_name: "宁德时代",
    target_symbol: "300750",
    direction: "watch",
    conviction: 0.5,
    sentiment_score: 0.05,
    time_horizon_hint: "swing",
    actionability: "informational",
  },
  evidence: [
    {
      evidence_span_id: "EV-trader_ji-002-a",
      char_start: 12,
      char_end: 24,
      text: "跌到 180 下方再看",
      confidence: 0.79,
      span_type: "condition",
    },
  ],
  source_text:
    "宁德时代等一个回调，现在追高不划算，跌到 180 下方再看，没到价格不动。",
  source_published_at: "2026-03-25T15:05:00+08:00",
  backtest: {
    return_pct: 0.0,
    holding_days: 0,
    exit_reason: "time_exit",
    max_drawdown_pct: 0.0,
    sharpe_ratio: 0.0,
    backtest_period: "—（未触发建仓）",
  },
  rlhf: {
    rating: 4,
    is_correct: true,
    corrected_direction: null,
    corrections: [],
    reviewer_id: "reviewer_demo",
    reviewed_at: "2026-03-26T10:12:00+08:00",
    review_notes: "watchlist 判定准确，价格条件清晰。",
  },
};

// ---- value_laozhang / 价值老张 — 长线价值 -----------------------------------

const TA_LZ_PINGAN: TradeAction = {
  trade_action_id: "TA-value_laozhang-001",
  timestamp: "2026-03-05T09:30:00+08:00",
  ticker: "601318",
  company_name: "中国平安",
  market: "SH",
  direction: "bullish",
  summary: "平安股息率到 6%，分批买入长期持有",
  action_chain: [
    {
      sequence: 1,
      action_type: "buy_and_hold",
      trigger_type: "indicator_signal",
      trigger_condition: "股息率 ≥ 6%",
      target_price_low: 44,
      target_price_high: 50,
      position_size_pct: 0.25,
      notes: "分三批，每跌 5% 加一批",
    },
  ],
  intent_id: "INT-value_laozhang-001",
  policy_id: "POL-global-base-v1",
  evidence_span_ids: ["EV-value_laozhang-001-a"],
  canonical_trace_status: "canonical",
  confidence: 0.85,
  validation_status: "verified",
  model_version: "glm-5.1",
  extraction_method: "f3_intent + f4_policy + f5_execute",
  execution_timing: {
    intent_published_at: "2026-03-05T07:40:00+08:00",
    intent_effective_at: "2026-03-05T09:30:00+08:00",
    action_decision_at: "2026-03-05T09:30:00+08:00",
    action_executable_at: "2026-03-05T09:30:00+08:00",
    market: "SH",
    timezone: "Asia/Shanghai",
    market_session_at_publish: "pre_market",
  },
  intent: {
    intent_id: "INT-value_laozhang-001",
    target_name: "中国平安",
    target_symbol: "601318",
    direction: "initiate_long",
    conviction: 0.82,
    sentiment_score: 0.55,
    time_horizon_hint: "long_term",
    actionability: "actionable",
  },
  evidence: [
    {
      evidence_span_id: "EV-value_laozhang-001-a",
      char_start: 9,
      char_end: 25,
      text: "股息率到 6% 就是值得长期拿的位置",
      confidence: 0.86,
      span_type: "claim",
    },
  ],
  source_text:
    "保险这块，平安股息率到 6% 就是值得长期拿的位置，估值在底部区域，分批买，拿三年。",
  source_published_at: "2026-03-05T07:40:00+08:00",
  backtest: {
    return_pct: 0.182,
    holding_days: 64,
    exit_reason: "time_exit",
    max_drawdown_pct: -0.041,
    sharpe_ratio: 1.12,
    backtest_period: "2026-03-05 — 2026-05-08",
  },
  rlhf: {
    rating: 5,
    is_correct: true,
    corrected_direction: null,
    corrections: [],
    reviewer_id: "reviewer_demo",
    reviewed_at: "2026-03-10T11:00:00+08:00",
    review_notes: "逻辑与证据高度一致，长线判断稳健。",
  },
};

const TA_LZ_CMB: TradeAction = {
  trade_action_id: "TA-value_laozhang-002",
  timestamp: "2026-04-02T09:30:00+08:00",
  ticker: "600036",
  company_name: "招商银行",
  market: "SH",
  direction: "bullish",
  summary: "招行回调到 PB 0.9 以下逢低加仓",
  action_chain: [
    {
      sequence: 1,
      action_type: "long",
      trigger_type: "price_threshold",
      trigger_condition: "PB 跌破 0.9",
      target_price_low: 38,
      target_price_high: 42,
      position_size_pct: 0.2,
      notes: "estimate",
    },
  ],
  intent_id: "INT-value_laozhang-002",
  policy_id: "POL-global-base-v1",
  evidence_span_ids: ["EV-value_laozhang-002-a"],
  canonical_trace_status: "canonical",
  confidence: 0.8,
  validation_status: "verified",
  model_version: "glm-5.1",
  extraction_method: "f3_intent + f4_policy + f5_execute",
  execution_timing: {
    intent_published_at: "2026-04-02T08:10:00+08:00",
    intent_effective_at: "2026-04-02T09:30:00+08:00",
    action_decision_at: "2026-04-02T09:30:00+08:00",
    action_executable_at: "2026-04-02T09:30:00+08:00",
    market: "SH",
    timezone: "Asia/Shanghai",
    market_session_at_publish: "pre_market",
  },
  intent: {
    intent_id: "INT-value_laozhang-002",
    target_name: "招商银行",
    target_symbol: "600036",
    direction: "add",
    conviction: 0.74,
    sentiment_score: 0.45,
    time_horizon_hint: "long_term",
    actionability: "actionable",
  },
  evidence: [
    {
      evidence_span_id: "EV-value_laozhang-002-a",
      char_start: 8,
      char_end: 22,
      text: "破净就是难得的加仓机会",
      confidence: 0.83,
      span_type: "rationale",
    },
  ],
  source_text:
    "银行股里招行最优质，破净就是难得的加仓机会，PB 跌到 0.9 以下我会继续买。",
  source_published_at: "2026-04-02T08:10:00+08:00",
  backtest: {
    return_pct: 0.094,
    holding_days: 36,
    exit_reason: "time_exit",
    max_drawdown_pct: -0.033,
    sharpe_ratio: 0.97,
    backtest_period: "2026-04-02 — 2026-05-08",
  },
  rlhf: {
    rating: 4,
    is_correct: true,
    corrected_direction: null,
    corrections: [],
    reviewer_id: "reviewer_demo",
    reviewed_at: "2026-04-08T09:40:00+08:00",
    review_notes: "稳健，触发条件明确。",
  },
};

// ---- trend_hunter_k / 趋势猎手K — 动量趋势 ----------------------------------

const TA_K_EASTMONEY: TradeAction = {
  trade_action_id: "TA-trend_hunter_k-001",
  timestamp: "2026-03-18T09:45:00+08:00",
  ticker: "300059",
  company_name: "东方财富",
  market: "SZ",
  direction: "bullish",
  summary: "东财放量突破平台，追入做多",
  action_chain: [
    {
      sequence: 1,
      action_type: "long",
      trigger_type: "breakout",
      trigger_condition: "放量突破 22 元平台",
      target_price_low: 22,
      target_price_high: 26,
      position_size_pct: 0.4,
      notes: "破位 20.5 立即止损",
    },
  ],
  intent_id: "INT-trend_hunter_k-001",
  policy_id: "POL-global-base-v1",
  evidence_span_ids: ["EV-trend_hunter_k-001-a"],
  canonical_trace_status: "canonical",
  confidence: 0.68,
  validation_status: "under_review",
  model_version: "glm-5.1",
  extraction_method: "f3_intent + f4_policy + f5_execute",
  execution_timing: {
    intent_published_at: "2026-03-18T09:40:00+08:00",
    intent_effective_at: "2026-03-18T09:45:00+08:00",
    action_decision_at: "2026-03-18T09:45:00+08:00",
    action_executable_at: "2026-03-18T09:50:00+08:00",
    market: "SZ",
    timezone: "Asia/Shanghai",
    market_session_at_publish: "regular",
  },
  intent: {
    intent_id: "INT-trend_hunter_k-001",
    target_name: "东方财富",
    target_symbol: "300059",
    direction: "initiate_long",
    conviction: 0.65,
    sentiment_score: 0.7,
    time_horizon_hint: "intraday",
    actionability: "actionable",
  },
  evidence: [
    {
      evidence_span_id: "EV-trend_hunter_k-001-a",
      char_start: 6,
      char_end: 20,
      text: "放量突破平台就是主升浪起点",
      confidence: 0.72,
      span_type: "claim",
    },
  ],
  source_text:
    "东方财富放量突破平台就是主升浪起点，量能不退就拿着，破位就走，别犹豫。",
  source_published_at: "2026-03-18T09:40:00+08:00",
  backtest: {
    return_pct: -0.061,
    holding_days: 9,
    exit_reason: "stop_loss",
    max_drawdown_pct: -0.118,
    sharpe_ratio: 0.31,
    backtest_period: "2026-03-18 — 2026-03-27",
  },
  rlhf: {
    rating: 2,
    is_correct: false,
    corrected_direction: "neutral",
    corrections: ["突破后未跟随，方向应判 neutral", "时间周期偏短，假突破风险高"],
    reviewer_id: "reviewer_demo",
    reviewed_at: "2026-03-28T16:20:00+08:00",
    review_notes: "假突破，止损正确但入场逻辑偏激进。",
  },
};

const TA_K_BYD: TradeAction = {
  trade_action_id: "TA-trend_hunter_k-002",
  timestamp: "2026-04-15T13:05:00+08:00",
  ticker: "002594",
  company_name: "比亚迪",
  market: "SZ",
  direction: "risk_warning",
  summary: "比亚迪跌破年线，趋势走坏先规避",
  action_chain: [
    {
      sequence: 1,
      action_type: "close_long",
      trigger_type: "indicator_signal",
      trigger_condition: "跌破年线且 MACD 死叉",
      target_price_low: null,
      target_price_high: null,
      position_size_pct: null,
      notes: "清仓规避",
    },
  ],
  intent_id: "INT-trend_hunter_k-002",
  policy_id: "POL-global-base-v1",
  evidence_span_ids: ["EV-trend_hunter_k-002-a"],
  canonical_trace_status: "canonical",
  confidence: 0.74,
  validation_status: "verified",
  model_version: "glm-5.1",
  extraction_method: "f3_intent + f4_policy + f5_execute",
  execution_timing: {
    intent_published_at: "2026-04-15T12:30:00+08:00",
    intent_effective_at: "2026-04-15T13:00:00+08:00",
    action_decision_at: "2026-04-15T13:00:00+08:00",
    action_executable_at: "2026-04-15T13:05:00+08:00",
    market: "SZ",
    timezone: "Asia/Shanghai",
    market_session_at_publish: "regular",
  },
  intent: {
    intent_id: "INT-trend_hunter_k-002",
    target_name: "比亚迪",
    target_symbol: "002594",
    direction: "exit",
    conviction: 0.7,
    sentiment_score: -0.5,
    time_horizon_hint: "swing",
    actionability: "actionable",
  },
  evidence: [
    {
      evidence_span_id: "EV-trend_hunter_k-002-a",
      char_start: 5,
      char_end: 17,
      text: "跌破年线趋势就走坏了",
      confidence: 0.78,
      span_type: "claim",
    },
  ],
  source_text:
    "比亚迪跌破年线趋势就走坏了，不要抄底，等右侧信号，现在拿着的先减。",
  source_published_at: "2026-04-15T12:30:00+08:00",
  backtest: {
    return_pct: 0.071,
    holding_days: 23,
    exit_reason: "signal_reversal",
    max_drawdown_pct: -0.028,
    sharpe_ratio: 0.66,
    backtest_period: "2026-04-15 — 2026-05-08",
  },
  rlhf: {
    rating: 4,
    is_correct: true,
    corrected_direction: null,
    corrections: [],
    reviewer_id: "reviewer_demo",
    reviewed_at: "2026-04-20T10:05:00+08:00",
    review_notes: "风险提示及时，规避正确。",
  },
};

// ---- hk_veteran / 港股老兵 — 港股 -------------------------------------------

const TA_HK_TENCENT: TradeAction = {
  trade_action_id: "TA-hk_veteran-001",
  timestamp: "2026-03-09T09:35:00+08:00",
  ticker: "00700",
  company_name: "腾讯控股",
  market: "HK",
  direction: "bullish",
  summary: "腾讯回购托底，回调到 380 港元分批买",
  action_chain: [
    {
      sequence: 1,
      action_type: "long",
      trigger_type: "support_resistance",
      trigger_condition: "回调至 380 港元支撑",
      target_price_low: 372,
      target_price_high: 400,
      position_size_pct: 0.25,
      notes: "estimate",
    },
  ],
  intent_id: "INT-hk_veteran-001",
  policy_id: "POL-global-base-v1",
  evidence_span_ids: ["EV-hk_veteran-001-a"],
  canonical_trace_status: "canonical",
  confidence: 0.79,
  validation_status: "verified",
  model_version: "glm-5.1",
  extraction_method: "f3_intent + f4_policy + f5_execute",
  execution_timing: {
    intent_published_at: "2026-03-09T08:00:00+08:00",
    intent_effective_at: "2026-03-09T09:30:00+08:00",
    action_decision_at: "2026-03-09T09:30:00+08:00",
    action_executable_at: "2026-03-09T09:35:00+08:00",
    market: "HK",
    timezone: "Asia/Hong_Kong",
    market_session_at_publish: "pre_market",
  },
  intent: {
    intent_id: "INT-hk_veteran-001",
    target_name: "腾讯控股",
    target_symbol: "00700",
    direction: "initiate_long",
    conviction: 0.76,
    sentiment_score: 0.5,
    time_horizon_hint: "position",
    actionability: "actionable",
  },
  evidence: [
    {
      evidence_span_id: "EV-hk_veteran-001-a",
      char_start: 7,
      char_end: 23,
      text: "每天回购就是给股价托底",
      confidence: 0.8,
      span_type: "rationale",
    },
  ],
  source_text:
    "腾讯这种公司，每天回购就是给股价托底，回调到 380 港元附近分批买，估值不贵。",
  source_published_at: "2026-03-09T08:00:00+08:00",
  backtest: {
    return_pct: 0.086,
    holding_days: 48,
    exit_reason: "time_exit",
    max_drawdown_pct: -0.037,
    sharpe_ratio: 0.74,
    backtest_period: "2026-03-09 — 2026-05-08",
  },
  rlhf: {
    rating: 4,
    is_correct: true,
    corrected_direction: null,
    corrections: [],
    reviewer_id: "reviewer_demo",
    reviewed_at: "2026-03-14T15:30:00+08:00",
    review_notes: "港股龙头逻辑清晰，支撑位合理。",
  },
};

const TA_HK_ALIBABA: TradeAction = {
  trade_action_id: "TA-hk_veteran-002",
  timestamp: "2026-04-10T11:20:00+08:00",
  ticker: "09988",
  company_name: "阿里巴巴",
  market: "HK",
  direction: "watchlist",
  summary: "阿里观察云业务拆分进展，暂不动",
  action_chain: [
    {
      sequence: 1,
      action_type: "watch",
      trigger_type: "news_event",
      trigger_condition: "云业务拆分落地",
      target_price_low: null,
      target_price_high: null,
      position_size_pct: null,
      notes: "等催化",
    },
  ],
  intent_id: "INT-hk_veteran-002",
  policy_id: "POL-global-base-v1",
  evidence_span_ids: ["EV-hk_veteran-002-a"],
  canonical_trace_status: "canonical",
  confidence: 0.66,
  validation_status: "verified",
  model_version: "glm-5.1",
  extraction_method: "f3_intent + f4_policy + f5_execute",
  execution_timing: {
    intent_published_at: "2026-04-10T11:00:00+08:00",
    intent_effective_at: "2026-04-10T13:00:00+08:00",
    action_decision_at: "2026-04-10T13:00:00+08:00",
    action_executable_at: "2026-04-10T13:00:00+08:00",
    market: "HK",
    timezone: "Asia/Hong_Kong",
    market_session_at_publish: "regular",
  },
  intent: {
    intent_id: "INT-hk_veteran-002",
    target_name: "阿里巴巴",
    target_symbol: "09988",
    direction: "watch",
    conviction: 0.48,
    sentiment_score: 0.15,
    time_horizon_hint: "position",
    actionability: "informational",
  },
  evidence: [
    {
      evidence_span_id: "EV-hk_veteran-002-a",
      char_start: 6,
      char_end: 20,
      text: "拆分落地才是真正的催化",
      confidence: 0.71,
      span_type: "condition",
    },
  ],
  source_text:
    "阿里现在拆分落地才是真正的催化，没落地之前估值修复有限，先观察，不急。",
  source_published_at: "2026-04-10T11:00:00+08:00",
  backtest: {
    return_pct: 0.0,
    holding_days: 0,
    exit_reason: "time_exit",
    max_drawdown_pct: 0.0,
    sharpe_ratio: 0.0,
    backtest_period: "—（未触发建仓）",
  },
  rlhf: {
    rating: 3,
    is_correct: true,
    corrected_direction: null,
    corrections: ["可补充催化时间窗口"],
    reviewer_id: "reviewer_demo",
    reviewed_at: "2026-04-15T09:50:00+08:00",
    review_notes: "观望判断合理，条件略宽泛。",
  },
};

// ---- sector_alpha / 赛道阿尔法 — 行业轮动 -----------------------------------

const TA_SA_SMIC: TradeAction = {
  trade_action_id: "TA-sector_alpha-001",
  timestamp: "2026-03-20T09:35:00+08:00",
  ticker: "688981",
  company_name: "中芯国际",
  market: "SH",
  direction: "bullish",
  summary: "国产替代加速，半导体赛道超配做多",
  action_chain: [
    {
      sequence: 1,
      action_type: "long",
      trigger_type: "news_event",
      trigger_condition: "国产替代政策催化",
      target_price_low: 52,
      target_price_high: 64,
      position_size_pct: 0.35,
      notes: "赛道超配，分两批",
    },
  ],
  intent_id: "INT-sector_alpha-001",
  policy_id: "POL-global-base-v1",
  evidence_span_ids: ["EV-sector_alpha-001-a"],
  canonical_trace_status: "canonical",
  confidence: 0.73,
  validation_status: "verified",
  model_version: "glm-5.1",
  extraction_method: "f3_intent + f4_policy + f5_execute",
  execution_timing: {
    intent_published_at: "2026-03-20T08:30:00+08:00",
    intent_effective_at: "2026-03-20T09:30:00+08:00",
    action_decision_at: "2026-03-20T09:30:00+08:00",
    action_executable_at: "2026-03-20T09:35:00+08:00",
    market: "SH",
    timezone: "Asia/Shanghai",
    market_session_at_publish: "pre_market",
  },
  intent: {
    intent_id: "INT-sector_alpha-001",
    target_name: "中芯国际",
    target_symbol: "688981",
    direction: "initiate_long",
    conviction: 0.69,
    sentiment_score: 0.65,
    time_horizon_hint: "position",
    actionability: "actionable",
  },
  evidence: [
    {
      evidence_span_id: "EV-sector_alpha-001-a",
      char_start: 8,
      char_end: 22,
      text: "国产替代是未来三年主线",
      confidence: 0.75,
      span_type: "claim",
    },
  ],
  source_text:
    "半导体这条赛道，国产替代是未来三年主线，中芯国际是核心标的，回调就是加仓机会。",
  source_published_at: "2026-03-20T08:30:00+08:00",
  backtest: {
    return_pct: 0.156,
    holding_days: 49,
    exit_reason: "target_reached",
    max_drawdown_pct: -0.094,
    sharpe_ratio: 0.58,
    backtest_period: "2026-03-20 — 2026-05-08",
  },
  rlhf: {
    rating: 3,
    is_correct: true,
    corrected_direction: null,
    corrections: ["波动较大，建议提示回撤风险"],
    reviewer_id: "reviewer_demo",
    reviewed_at: "2026-03-26T14:00:00+08:00",
    review_notes: "赛道判断方向对，但波动控制需加强。",
  },
};

const TA_SA_MINDRAY: TradeAction = {
  trade_action_id: "TA-sector_alpha-002",
  timestamp: "2026-04-22T09:30:00+08:00",
  ticker: "300760",
  company_name: "迈瑞医疗",
  market: "SZ",
  direction: "bullish",
  summary: "医疗器械轮动，迈瑞估值切换做多",
  action_chain: [
    {
      sequence: 1,
      action_type: "long",
      trigger_type: "indicator_signal",
      trigger_condition: "PE 回到 25x 以下",
      target_price_low: 230,
      target_price_high: 270,
      position_size_pct: 0.2,
      notes: "estimate",
    },
  ],
  intent_id: "INT-sector_alpha-002",
  policy_id: "POL-global-base-v1",
  evidence_span_ids: ["EV-sector_alpha-002-a"],
  canonical_trace_status: "canonical",
  confidence: 0.7,
  validation_status: "verified",
  model_version: "glm-5.1",
  extraction_method: "f3_intent + f4_policy + f5_execute",
  execution_timing: {
    intent_published_at: "2026-04-22T08:20:00+08:00",
    intent_effective_at: "2026-04-22T09:30:00+08:00",
    action_decision_at: "2026-04-22T09:30:00+08:00",
    action_executable_at: "2026-04-22T09:30:00+08:00",
    market: "SZ",
    timezone: "Asia/Shanghai",
    market_session_at_publish: "pre_market",
  },
  intent: {
    intent_id: "INT-sector_alpha-002",
    target_name: "迈瑞医疗",
    target_symbol: "300760",
    direction: "initiate_long",
    conviction: 0.67,
    sentiment_score: 0.5,
    time_horizon_hint: "position",
    actionability: "actionable",
  },
  evidence: [
    {
      evidence_span_id: "EV-sector_alpha-002-a",
      char_start: 9,
      char_end: 21,
      text: "估值切换到了买点",
      confidence: 0.72,
      span_type: "claim",
    },
  ],
  source_text:
    "医疗器械龙头迈瑞，估值切换到了买点，业绩确定性高，资金会从高位赛道轮过来。",
  source_published_at: "2026-04-22T08:20:00+08:00",
  backtest: {
    return_pct: 0.067,
    holding_days: 16,
    exit_reason: "time_exit",
    max_drawdown_pct: -0.045,
    sharpe_ratio: 0.61,
    backtest_period: "2026-04-22 — 2026-05-08",
  },
  rlhf: {
    rating: 3,
    is_correct: true,
    corrected_direction: null,
    corrections: [],
    reviewer_id: "reviewer_demo",
    reviewed_at: "2026-04-28T13:10:00+08:00",
    review_notes: "轮动逻辑成立。",
  },
};

// ---- KOL roster -------------------------------------------------------------

export const KOLS: Kol[] = [
  {
    id: "trader_ji",
    handle: "trader_ji",
    name: "老纪",
    style: "个股短线",
    rating: 3.3,
    backtest_count: 2,
    tickers: ["600519", "300750"],
    period: "2026-03-02 — 2026-05-08",
    blurb: "A 股个股短线，重支撑/突破与仓位管理。",
    metrics: {
      cum_return: 0.214,
      annualized: 0.214,
      sharpe: 0.74,
      max_drawdown: -0.08,
      win_rate: 0.667,
      signal_count: 3,
    },
    capability: [
      { label: "逻辑严密", value: 3.3 },
      { label: "一致性", value: 2.9 },
      { label: "时效性", value: 3.5 },
      { label: "深度", value: 3.4 },
      { label: "落地性", value: 3.5 },
    ],
    series: series([0, 3.2, 6.1, 4.8, 8.5, 11.2, 9.0, 14.1, 17.5, 16.0, 19.8, 21.4]),
    trade_actions: [TA_JI_MAOTAI, TA_JI_CATL],
  },
  {
    id: "value_laozhang",
    handle: "value_laozhang",
    name: "价值老张",
    style: "长线价值",
    rating: 3.8,
    backtest_count: 2,
    tickers: ["601318", "600036"],
    period: "2026-03-02 — 2026-05-08",
    blurb: "低估值蓝筹长期持有，重股息与安全边际。",
    metrics: {
      cum_return: 0.152,
      annualized: 0.152,
      sharpe: 1.05,
      max_drawdown: -0.045,
      win_rate: 0.72,
      signal_count: 2,
    },
    capability: [
      { label: "逻辑严密", value: 4.1 },
      { label: "一致性", value: 4.0 },
      { label: "时效性", value: 2.8 },
      { label: "深度", value: 3.9 },
      { label: "落地性", value: 3.6 },
    ],
    series: series([0, 1.8, 3.5, 4.2, 5.8, 7.0, 8.3, 9.5, 11.0, 12.4, 13.8, 15.2]),
    trade_actions: [TA_LZ_PINGAN, TA_LZ_CMB],
  },
  {
    id: "trend_hunter_k",
    handle: "trend_hunter_k",
    name: "趋势猎手K",
    style: "动量趋势",
    rating: 2.6,
    backtest_count: 2,
    tickers: ["300059", "002594"],
    period: "2026-03-02 — 2026-05-08",
    blurb: "突破/动量短线，追涨杀跌、严格止损。",
    metrics: {
      cum_return: 0.084,
      annualized: 0.084,
      sharpe: 0.42,
      max_drawdown: -0.142,
      win_rate: 0.51,
      signal_count: 2,
    },
    capability: [
      { label: "逻辑严密", value: 2.4 },
      { label: "一致性", value: 2.2 },
      { label: "时效性", value: 3.8 },
      { label: "深度", value: 2.1 },
      { label: "落地性", value: 3.2 },
    ],
    series: series([0, 4.5, 8.0, 2.1, 6.5, 11.0, 3.5, 7.8, 12.5, 5.0, 9.2, 8.4]),
    trade_actions: [TA_K_EASTMONEY, TA_K_BYD],
  },
  {
    id: "hk_veteran",
    handle: "hk_veteran",
    name: "港股老兵",
    style: "港股",
    rating: 3.1,
    backtest_count: 2,
    tickers: ["00700", "09988"],
    period: "2026-03-02 — 2026-05-08",
    blurb: "港股龙头，重回购、估值与基本面催化。",
    metrics: {
      cum_return: 0.059,
      annualized: 0.059,
      sharpe: 0.68,
      max_drawdown: -0.039,
      win_rate: 0.6,
      signal_count: 2,
    },
    capability: [
      { label: "逻辑严密", value: 3.4 },
      { label: "一致性", value: 3.3 },
      { label: "时效性", value: 2.6 },
      { label: "深度", value: 3.5 },
      { label: "落地性", value: 3.0 },
    ],
    series: series([0, 1.0, 2.2, 1.5, 2.8, 3.5, 3.0, 4.1, 4.8, 4.2, 5.5, 5.9]),
    trade_actions: [TA_HK_TENCENT, TA_HK_ALIBABA],
  },
  {
    id: "sector_alpha",
    handle: "sector_alpha",
    name: "赛道阿尔法",
    style: "行业轮动",
    rating: 2.9,
    backtest_count: 2,
    tickers: ["688981", "300760"],
    period: "2026-03-02 — 2026-05-08",
    blurb: "赛道与行业轮动，重产业趋势与资金切换。",
    metrics: {
      cum_return: 0.121,
      annualized: 0.121,
      sharpe: 0.55,
      max_drawdown: -0.11,
      win_rate: 0.58,
      signal_count: 2,
    },
    capability: [
      { label: "逻辑严密", value: 3.0 },
      { label: "一致性", value: 2.6 },
      { label: "时效性", value: 3.3 },
      { label: "深度", value: 3.2 },
      { label: "落地性", value: 2.9 },
    ],
    series: series([0, 5.0, 9.5, 6.0, 11.0, 14.5, 8.0, 13.0, 16.5, 10.5, 13.8, 12.1]),
    trade_actions: [TA_SA_SMIC, TA_SA_MINDRAY],
  },
];

/** The trade action used to walk the F0-F8 pipeline rail. */
export const PIPELINE_SAMPLE_KOL_ID = "trader_ji";
export const PIPELINE_SAMPLE_TA_ID = "TA-trader_ji-001";

export const STAGE_DETAILS: StageDetail[] = [
  {
    id: "F0",
    name: "Intake",
    role: "规则",
    headline: "多源接入",
    what: "从飞书 / 微信公众号 / B站等渠道接入老纪的原帖，落为 ContentRecord 与原始归档，不做任何解析。",
    output: [
      { k: "content_id", v: "CR-feishu-20260312-0850" },
      { k: "source_channel", v: "feishu" },
      { k: "raw_archived", v: "true" },
    ],
    schema_ref: "schemas/contract.py: ContentRecord",
  },
  {
    id: "F1",
    name: "Standardize",
    role: "AI",
    headline: "内容标准化",
    what: "MiMo-V2.5 处理图片/截图，文本归一化为 ContentEnvelope + ContentBlock，并标注标准化质量与 provenance。",
    output: [
      { k: "envelope_id", v: "ENV-trader_ji-20260312" },
      { k: "blocks", v: "1 text block" },
      { k: "standardization_quality", v: "0.95" },
    ],
    schema_ref: "schemas/content_envelope.py: ContentEnvelope",
  },
  {
    id: "F2",
    name: "Anchor",
    role: "规则",
    headline: "实体 / 时间锚定",
    what: "解析实体「贵州茅台 → 600519」、时间锚点，并抽取证据片段 EvidenceSpan，记录字符区间。",
    output: [
      { k: "entity", v: "贵州茅台 → 600519 (SH)" },
      { k: "evidence_spans", v: "EV-…-001-a, EV-…-001-b" },
      { k: "char_range", v: "[10, 28], [38, 46]" },
    ],
    schema_ref: "schemas/evidence.py: EvidenceSpan",
  },
  {
    id: "F3",
    name: "Intent",
    role: "AI",
    headline: "投资意图",
    what: "LLM 从证据片段提取结构化投资意图：方向、信念度、时间跨度——止于 Intent，不生成交易动作。",
    output: [
      { k: "intent_id", v: "INT-trader_ji-001" },
      { k: "direction", v: "initiate_long" },
      { k: "conviction", v: "0.78" },
      { k: "time_horizon", v: "swing" },
    ],
    schema_ref: "schemas/investment_intent.py: NormalizedInvestmentIntent",
  },
  {
    id: "F4",
    name: "Policy",
    role: "规则",
    headline: "策略映射",
    what: "确定性规则引擎把 Intent 映射为可执行策略：建仓节奏、触发条件、仓位上限——无 LLM。",
    output: [
      { k: "policy_id", v: "POL-global-base-v1" },
      { k: "position_cap", v: "≤ 50%" },
      { k: "tranches", v: "2" },
    ],
    schema_ref: "schemas/policy.py: PolicyMappingResult",
  },
  {
    id: "F5",
    name: "Execute",
    role: "AI",
    headline: "TradeAction",
    what: "生成 canonical TradeAction：携带 intent_id / policy_id / evidence_span_ids 与四时钟执行时间，证据链不断裂。",
    output: [
      { k: "trade_action_id", v: "TA-trader_ji-001" },
      { k: "direction", v: "bullish" },
      { k: "canonical_trace_status", v: "canonical" },
      { k: "executable_at", v: "09:35 (次开盘)" },
    ],
    schema_ref: "schemas/trade_action.py: TradeAction",
  },
  {
    id: "F6",
    name: "Review",
    role: "人",
    headline: "人工复核",
    what: "进入回测前，人类在 F6 复核台裁决：评分、is_correct、字段级修正，记录为 RLHFFeedback。",
    output: [
      { k: "rating", v: "4 / 5" },
      { k: "is_correct", v: "true" },
      { k: "reviewer_id", v: "reviewer_demo" },
    ],
    schema_ref: "schemas/trade_action.py: RLHFFeedback",
  },
  {
    id: "F7",
    name: "Timeline",
    role: "规则",
    headline: "观点编年史",
    what: "把同一标的上的历次观点串成 ViewpointState 时间线，跟踪立场变化与持仓演进。",
    output: [
      { k: "ticker", v: "600519" },
      { k: "state", v: "open_long" },
      { k: "viewpoints", v: "1" },
    ],
    schema_ref: "schemas/lineage.py: ViewpointState",
  },
  {
    id: "F8",
    name: "Backtest",
    role: "规则",
    headline: "回测评分",
    what: "以完全跟单者视角回测，次开盘成交、显式费用/滑点，输出可审计绩效，并回算 KOL 评分。",
    output: [
      { k: "return_pct", v: "+12.3%" },
      { k: "holding_days", v: "35" },
      { k: "sharpe_ratio", v: "0.91" },
      { k: "exit_reason", v: "target_reached" },
    ],
    schema_ref: "schemas/trade_action.py: BacktestResult",
  },
];
