/**
 * Frozen, anonymized snapshot of REAL Finer OS F5 canonical TradeActions.
 * Generated by scripts/freeze (see scratchpad) from data/F5_executed/*.json:
 * real tickers / signal timing / KOL evidence quotes / F8 backtest outcomes are
 * preserved; the KOL identity is relabeled to an anonymous code. Sample-data,
 * single anonymized KOL — NOT a live feed.
 */
import type { KOLRadarData } from "./kol-radar";
import type { TradingStyleProfile } from "./contracts-style";
import raw from "./data.json";

/** Per-viewpoint canonical trace payload (F3 intent → F4 policy → F5 timing → F8 backtest). */
export interface AuditExecutionTiming {
  intentPublishedAt: string | null;
  intentEffectiveAt: string | null;
  actionDecisionAt: string | null;
  actionExecutableAt: string | null;
  market: string | null;
  timezone: string | null;
  session: string | null;
  timingPolicyId: string | null;
}

export interface AuditBacktest {
  returnPct: number | null;
  holdingDays: number | null;
  exitReason: string | null;
  exitPrice: number | null;
  maxDrawdownPct: number | null;
  period: string | null;
}

export interface AuditRecord {
  intentId: string | null;
  policyId: string | null;
  evidenceSpanIds: string[];
  traceStatus: string | null;
  conviction: number | null;
  confidence: number | null;
  extractionMethod: string | null;
  modelVersion: string | null;
  actionHint: string | null;
  tier: string | null;
  rationale: string | null;
  executionTiming: AuditExecutionTiming;
  backtest: AuditBacktest | null;
}

interface FrozenSnapshot {
  radar: KOLRadarData;
  tradingStyle: TradingStyleProfile;
  auditById: Record<string, AuditRecord>;
}

const snapshot = raw as unknown as FrozenSnapshot;

export const RADAR: KOLRadarData = snapshot.radar;
export const TRADING_STYLE: TradingStyleProfile = snapshot.tradingStyle;
export const AUDIT_BY_ID: Record<string, AuditRecord> = snapshot.auditById;

/** The single anonymized KOL id in the frozen snapshot. */
export const KOL_ID: string = snapshot.radar.kols[0]?.kolId ?? "";
