"""Broker entity registry loader — deterministic F2 append-only alias source.

``configs/entity_registry_broker.yaml`` is AUTO-GENERATED by
``scripts/build_broker_entity_registry.py`` from the broker research corpus
(reports.db (company_name, stock_code) pairs + the research repo's curated
``entities.yaml`` positive/negative rules).

Layering contract (must hold everywhere this module is consumed):

- The curated KOL registry (``finer.entity_registry.ENTITY_REGISTRY``) is the
  primary deterministic layer. Broker entries are APPENDED: an alias already
  present in the KOL registry is never overridden by a broker entry.
- Broker entries only carry tradable stocks (entity_type ``ticker``); they add
  no sector placeholders.
- Missing/empty YAML degrades to an empty registry — the deterministic scan
  then behaves exactly like the KOL-only baseline.
- Ambiguous bare aliases (common English words / legal suffixes / timezones:
  KEY, SE, ET, Target, Block...) are surfaced via
  ``load_context_required_aliases`` — the F2 deterministic scan must see an
  explicit ticker context before anchoring them. The set is the union of the
  generator's ``requires_context: true`` flags and (defense-in-depth, so stale
  YAMLs stay safe) ``entity_stoplist.is_ambiguous_broker_alias`` applied to
  every loaded broker alias. Curated KOL aliases are never context-gated here.

The loader caches by file mtime so long-lived processes pick up regenerated
registries without restart, while tests can point it at fixtures via the
``path`` parameter + ``clear_cache()``.
"""

from __future__ import annotations

import threading
from pathlib import Path
from typing import Dict, FrozenSet, Optional, Tuple

import yaml

from finer.entity_registry import ENTITY_REGISTRY, EntityEntry
from finer.enrichment.entity_stoplist import is_ambiguous_broker_alias
from finer.paths import REPO_ROOT

DEFAULT_BROKER_REGISTRY_PATH: Path = REPO_ROOT / "configs" / "entity_registry_broker.yaml"

_VALID_MARKETS = frozenset({"US", "CN", "HK", "TW", "JP"})


class _BrokerRegistrySnapshot:
    """Immutable snapshot of one parsed broker registry file."""

    __slots__ = ("entries", "generic_ticker_context_patterns", "context_required_aliases")

    def __init__(
        self,
        entries: Dict[str, EntityEntry],
        generic_ticker_context_patterns: Tuple[str, ...],
        context_required_aliases: FrozenSet[str],
    ) -> None:
        self.entries = entries
        self.generic_ticker_context_patterns = generic_ticker_context_patterns
        self.context_required_aliases = context_required_aliases


_EMPTY_SNAPSHOT = _BrokerRegistrySnapshot({}, (), frozenset())

_lock = threading.Lock()
_cache: dict[str, tuple[float, _BrokerRegistrySnapshot]] = {}


def clear_cache() -> None:
    """Drop all cached snapshots (test hook)."""
    with _lock:
        _cache.clear()


def _parse(path: Path) -> _BrokerRegistrySnapshot:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError):
        return _EMPTY_SNAPSHOT
    if not isinstance(data, dict):
        return _EMPTY_SNAPSHOT

    entries: Dict[str, EntityEntry] = {}
    context_required: set[str] = set()
    raw_entries = data.get("entries")
    if isinstance(raw_entries, dict):
        for alias, spec in raw_entries.items():
            if not isinstance(alias, str) or not alias.strip():
                continue
            if not isinstance(spec, dict):
                continue
            symbol = spec.get("symbol")
            market = spec.get("market")
            if not isinstance(symbol, str) or not symbol:
                continue
            if not isinstance(market, str) or market not in _VALID_MARKETS:
                continue
            # Append-only: curated KOL entries always win on alias conflicts.
            if alias in ENTITY_REGISTRY:
                continue
            entries[alias] = (symbol, market, "ticker")
            # Ambiguous bare aliases must carry an explicit ticker context.
            # Union of the generator flag and the load-time classifier so a
            # stale YAML (generated before the flag existed) is still gated.
            if spec.get("requires_context") is True or is_ambiguous_broker_alias(alias):
                context_required.add(alias)

    patterns: Tuple[str, ...] = ()
    negative = data.get("negative_rules")
    if isinstance(negative, dict):
        raw_patterns = negative.get("generic_ticker_context_patterns")
        if isinstance(raw_patterns, list):
            patterns = tuple(p for p in raw_patterns if isinstance(p, str) and p)

    return _BrokerRegistrySnapshot(entries, patterns, frozenset(context_required))


def _snapshot(path: Optional[Path] = None) -> _BrokerRegistrySnapshot:
    target = Path(path) if path is not None else DEFAULT_BROKER_REGISTRY_PATH
    try:
        mtime = target.stat().st_mtime
    except OSError:
        return _EMPTY_SNAPSHOT
    key = str(target)
    with _lock:
        cached = _cache.get(key)
        if cached is not None and cached[0] == mtime:
            return cached[1]
    snapshot = _parse(target)
    with _lock:
        _cache[key] = (mtime, snapshot)
    return snapshot


def load_broker_entries(path: Optional[Path] = None) -> Dict[str, EntityEntry]:
    """alias → (symbol, market, "ticker") from the generated broker registry.

    Aliases that collide with the curated KOL registry are already dropped
    here, so callers may merge blindly without risking overrides.
    """
    return _snapshot(path).entries


def load_generic_ticker_context_patterns(path: Optional[Path] = None) -> Tuple[str, ...]:
    """Report-title patterns near which numeric ticker-shaped hits are noise."""
    return _snapshot(path).generic_ticker_context_patterns


def load_context_required_aliases(path: Optional[Path] = None) -> FrozenSet[str]:
    """Broker aliases that may only anchor with an explicit ticker context.

    Union of the generated ``requires_context: true`` flags and the load-time
    ``is_ambiguous_broker_alias`` classifier, restricted to aliases actually
    loaded (KOL-priority drops apply first). Curated KOL registry aliases are
    never included.
    """
    return _snapshot(path).context_required_aliases


def merged_registry(path: Optional[Path] = None) -> Dict[str, EntityEntry]:
    """Deterministic-layer view: broker entries appended under the KOL registry.

    Dict-update order guarantees KOL priority: broker first, curated last.
    """
    merged: Dict[str, EntityEntry] = dict(load_broker_entries(path))
    merged.update(ENTITY_REGISTRY)
    return merged
